# Generated by Django 3.0.6 on 2020-05-15 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_details', models.TextField(max_length=200, null=True)),
                ('delivery_price', models.IntegerField(null=True)),
                ('delivered_time', models.TimeField(auto_now_add=True, null=True)),
                ('delivered_date', models.DateField(auto_now_add=True, null=True)),
                ('receiver_name', models.CharField(max_length=20, null=True)),
                ('receiver_address', models.TextField(max_length=100, null=True)),
                ('receiver_pin_code', models.CharField(max_length=7, null=True)),
                ('receiver_contact', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_completed', models.BooleanField(default=False, null=True)),
                ('is_cancelled', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=10, null=True)),
                ('address', models.TextField(max_length=100, null=True)),
                ('pin_code', models.CharField(max_length=7, null=True)),
                ('icon', models.ImageField(null=True, upload_to='images/')),
                ('verification_doc', models.FileField(null=True, upload_to='documents/')),
                ('payment_credentials', models.ImageField(null=True, upload_to='images/')),
                ('role', models.CharField(choices=[('SA', 'SA'), ('CA', 'CA'), ('DP', 'DP')], default='CA', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='images/')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rcustomer', to='admin_app.UserDetails')),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.Delivery')),
                ('delivery_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rdelivery_person', to='admin_app.UserDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('review', models.TextField(max_length=250, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fcustomer', to='admin_app.UserDetails')),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.Delivery')),
                ('delivery_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fdelivery_person', to='admin_app.UserDetails')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dcustomer', to='admin_app.UserDetails'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ddelivery_person', to='admin_app.UserDetails'),
        ),
        migrations.CreateModel(
            name='AssignedDeliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.Delivery')),
                ('delivery_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.UserDetails')),
            ],
        ),
    ]
