# Generated by Django 3.0.6 on 2020-05-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
