# Generated by Django 3.0.6 on 2020-05-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_delivery_delivery_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='payment_complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
