# Generated by Django 3.0.6 on 2020-05-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_delivery_payment_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='current_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Accepted', 'Accepted'), ('Picked', 'Picked'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=10),
        ),
    ]
