# Generated by Django 3.0.6 on 2020-05-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_delivery_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('FAST', 'FAST')], default='NORMAL', max_length=10),
        ),
    ]
