# Generated by Django 3.0.6 on 2020-05-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_delivery_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_person_availability',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('BUSY', 'BUSY')], default='AVAILABLE', max_length=20),
        ),
    ]
