# Generated by Django 3.0.6 on 2020-05-21 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_auto_20200519_2308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedDeliveries',
        ),
    ]
