# Generated by Django 3.0.6 on 2020-05-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_auto_20200526_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
