# Generated by Django 3.0.6 on 2020-05-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_userdetails_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
